airbnb_dbt_snowflake_project:
  outputs:
    dev:
      account: YKZCVNJ-VE03988
      database: AIRBNB
      password: StartPractising@6
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: sagarika99
      warehouse: COMPUTE_WH
  target: dev
